=== bio-tools/biotoolsShim/xml2genericxml-singletool/versions/biotools-3.3.0/biotools-3.3.0_framework_singletool.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2019 rel. 3 (x64) (http://www.altova.com) by Jon Ison (private) -->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
	<xs:element name="root">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="name" type="xs:string"/>
				<xs:element name="description" type="xs:string"/>
				<xs:element name="homepage" type="xs:anyURI"/>
				<xs:element name="biotoolsID" type="xs:string" minOccurs="0"/>
				<xs:element name="biotoolsCURIE" type="xs:string" minOccurs="0"/>
				<xs:element name="version" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="list-item" type="xs:string" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="otherID" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="list-item" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="value" type="xs:string"/>
										<xs:element name="type" type="xs:string" minOccurs="0"/>
										<xs:element name="version" type="xs:string" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="function" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="list-item" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="operation">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="list-item" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="uri" type="xs:anyURI" minOccurs="0"/>
																<xs:element name="term" type="xs:string" minOccurs="0"/>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="input" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="list-item" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="data">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="uri" type="xs:anyURI" minOccurs="0"/>
																			<xs:element name="term" type="xs:string" minOccurs="0"/>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
																<xs:element name="format" minOccurs="0">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="list-item" maxOccurs="unbounded">
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element name="uri" type="xs:anyURI" minOccurs="0"/>
																						<xs:element name="term" type="xs:string" minOccurs="0"/>
																					</xs:sequence>
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="output" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="list-item" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="data">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="uri" type="xs:anyURI" minOccurs="0"/>
																			<xs:element name="term" type="xs:string" minOccurs="0"/>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
																<xs:element name="format" minOccurs="0">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="list-item" maxOccurs="unbounded">
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element name="uri" type="xs:anyURI" minOccurs="0"/>
																						<xs:element name="term" type="xs:string" minOccurs="0"/>
																					</xs:sequence>
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="note" type="xs:string" minOccurs="0"/>
										<xs:element name="cmd" type="xs:string" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="toolType" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="list-item" type="xs:string" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="topic" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="list-item" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="uri" type="xs:anyURI" minOccurs="0"/>
										<xs:element name="term" type="xs:string" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="operatingSystem" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="list-item" type="xs:string" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="language" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="list-item" type="xs:string" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="license" type="xs:string" minOccurs="0"/>
				<xs:element name="collectionID" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="list-item" type="xs:string" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="maturity" type="xs:string" minOccurs="0"/>
				<xs:element name="cost" type="xs:string" minOccurs="0"/>
				<xs:element name="accessibility" type="xs:string" minOccurs="0"/>
				<xs:element name="elixirPlatform" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="list-item" type="xs:string" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="elixirCommunity" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="list-item" type="xs:string" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="elixirNode" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="list-item" type="xs:string" maxOccurs="unbounded"/>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="link" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="list-item" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="url" type="xs:anyURI"/>
										<xs:element name="type">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="list-item" type="xs:string" maxOccurs="unbounded"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="note" type="xs:string" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="download" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="list-item" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="url" type="xs:anyURI"/>
										<xs:element name="type" type="xs:string"/>
										<xs:element name="note" type="xs:string" minOccurs="0"/>
										<xs:element name="version" type="xs:string" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="documentation" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="list-item" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="url" type="xs:anyURI"/>
										<xs:element name="type">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="list-item" type="xs:string" maxOccurs="unbounded"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="note" type="xs:string" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="relation" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="list-item" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="biotoolsID" type="xs:string"/>
										<xs:element name="type" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="publication" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="list-item" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="doi" type="xs:string" minOccurs="0"/>
										<xs:element name="pmid" type="xs:string" minOccurs="0"/>
										<xs:element name="pmcid" type="xs:string" minOccurs="0"/>
										<xs:element name="type" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="list-item" type="xs:string" maxOccurs="unbounded"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="version" type="xs:string" minOccurs="0"/>
										<xs:element name="note" type="xs:string" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
				<xs:element name="credit" minOccurs="0">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="list-item" maxOccurs="unbounded">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="name" type="xs:string" minOccurs="0"/>
										<xs:element name="email" type="xs:string" minOccurs="0"/>
										<xs:element name="url" type="xs:anyURI" minOccurs="0"/>
										<xs:element name="orcidid" type="xs:string" minOccurs="0"/>
										<xs:element name="gridid" type="xs:string" minOccurs="0"/>
										<xs:element name="rorid" type="xs:string" minOccurs="0"/>
										<xs:element name="fundrefid" type="xs:string" minOccurs="0"/>
										<xs:element name="typeEntity" type="xs:string" minOccurs="0"/>
										<xs:element name="typeRole" minOccurs="0">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="list-item" type="xs:string" maxOccurs="unbounded"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
										<xs:element name="note" type="xs:string" minOccurs="0"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== bio-tools/biotoolsShim/genericxml2xml-singletool/versions/biotools-3.3.0/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--Sample XML file generated by XMLSpy v2019 rel. 3 (x64) (http://www.altova.com)-->
<root xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///E:/repos/GitHub/biotoolsShim/genericxml2xml-singletool/versions/biotools-3.3.0/biotools-3.3.0_framework_singletool.xsd">
	<name>String</name>
	<description>String</description>
	<homepage>http://www.altova.com/</homepage>
	<biotoolsID>String</biotoolsID>
	<biotoolsCURIE>String</biotoolsCURIE>
	<version>
		<list-item>String</list-item>
		<list-item>String</list-item>
	</version>
	<otherID>
		<list-item>
			<value>String</value>
			<type>String</type>
			<version>String</version>
		</list-item>
		<list-item>
			<value>String</value>
			<type>String</type>
			<version>String</version>
		</list-item>
	</otherID>
	<function>
		<list-item>
			<operation>
				<list-item>
					<uri>http://www.altova.com/</uri>
					<term>String</term>
				</list-item>
				<list-item>
					<uri>http://www.altova.com/</uri>
					<term>String</term>
				</list-item>
			</operation>
			<input>
				<list-item>
					<data>
						<uri>http://www.altova.com/</uri>
						<term>String</term>
					</data>
					<format>
						<list-item>
							<uri>http://www.altova.com/</uri>
							<term>String</term>
						</list-item>
						<list-item>
							<uri>http://www.altova.com/</uri>
							<term>String</term>
						</list-item>
					</format>
				</list-item>
				<list-item>
					<data>
						<uri>http://www.altova.com/</uri>
						<term>String</term>
					</data>
					<format>
						<list-item>
							<uri>http://www.altova.com/</uri>
							<term>String</term>
						</list-item>
						<list-item>
							<uri>http://www.altova.com/</uri>
							<term>String</term>
						</list-item>
					</format>
				</list-item>
			</input>
			<output>
				<list-item>
					<data>
						<uri>http://www.altova.com/</uri>
						<term>String</term>
					</data>
					<format>
						<list-item>
							<uri>http://www.altova.com/</uri>
							<term>String</term>
						</list-item>
						<list-item>
							<uri>http://www.altova.com/</uri>
							<term>String</term>
						</list-item>
					</format>
				</list-item>
				<list-item>
					<data>
						<uri>http://www.altova.com/</uri>
						<term>String</term>
					</data>
					<format>
						<list-item>
							<uri>http://www.altova.com/</uri>
							<term>String</term>
						</list-item>
						<list-item>
							<uri>http://www.altova.com/</uri>
							<term>String</term>
						</list-item>
					</format>
				</list-item>
			</output>
			<note>String</note>
			<cmd>String</cmd>
		</list-item>
		<list-item>
			<operation>
				<list-item>
					<uri>http://www.altova.com/</uri>
					<term>String</term>
				</list-item>
				<list-item>
					<uri>http://www.altova.com/</uri>
					<term>String</term>
				</list-item>
			</operation>
			<input>
				<list-item>
					<data>
						<uri>http://www.altova.com/</uri>
						<term>String</term>
					</data>
					<format>
						<list-item>
							<uri>http://www.altova.com/</uri>
							<term>String</term>
						</list-item>
						<list-item>
							<uri>http://www.altova.com/</uri>
							<term>String</term>
						</list-item>
					</format>
				</list-item>
				<list-item>
					<data>
						<uri>http://www.altova.com/</uri>
						<term>String</term>
					</data>
					<format>
						<list-item>
							<uri>http://www.altova.com/</uri>
							<term>String</term>
						</list-item>
						<list-item>
							<uri>http://www.altova.com/</uri>
							<term>String</term>
						</list-item>
					</format>
				</list-item>
			</input>
			<output>
				<list-item>
					<data>
						<uri>http://www.altova.com/</uri>
						<term>String</term>
					</data>
					<format>
						<list-item>
							<uri>http://www.altova.com/</uri>
							<term>String</term>
						</list-item>
						<list-item>
							<uri>http://www.altova.com/</uri>
							<term>String</term>
						</list-item>
					</format>
				</list-item>
				<list-item>
					<data>
						<uri>http://www.altova.com/</uri>
						<term>String</term>
					</data>
					<format>
						<list-item>
							<uri>http://www.altova.com/</uri>
							<term>String</term>
						</list-item>
						<list-item>
							<uri>http://www.altova.com/</uri>
							<term>String</term>
						</list-item>
					</format>
				</list-item>
			</output>
			<note>String</note>
			<cmd>String</cmd>
		</list-item>
	</function>
	<toolType>
		<list-item>String</list-item>
		<list-item>String</list-item>
	</toolType>
	<topic>
		<list-item>
			<uri>http://www.altova.com/</uri>
			<term>String</term>
		</list-item>
		<list-item>
			<uri>http://www.altova.com/</uri>
			<term>String</term>
		</list-item>
	</topic>
	<operatingSystem>
		<list-item>String</list-item>
		<list-item>String</list-item>
	</operatingSystem>
	<language>
		<list-item>String</list-item>
		<list-item>String</list-item>
	</language>
	<license>String</license>
	<collectionID>
		<list-item>String</list-item>
		<list-item>String</list-item>
	</collectionID>
	<maturity>String</maturity>
	<cost>String</cost>
	<accessibility>text</accessibility>
	<elixirPlatform>
		<list-item>String</list-item>
		<list-item>String</list-item>
	</elixirPlatform>
	<elixirCommunity>
		<list-item>String</list-item>
		<list-item>String</list-item>
	</elixirCommunity>
	<elixirNode>
		<list-item>String</list-item>
		<list-item>String</list-item>
	</elixirNode>
	<link>
		<list-item>
			<url>http://www.altova.com/</url>
			<type>
				<list-item>String</list-item>
				<list-item>String</list-item>
			</type>
			<note>String</note>
		</list-item>
		<list-item>
			<url>http://www.altova.com/</url>
			<type>
				<list-item>String</list-item>
				<list-item>String</list-item>
			</type>
			<note>String</note>
		</list-item>
	</link>
	<download>
		<list-item>
			<url>http://www.altova.com/</url>
			<type>String</type>
			<note>String</note>
			<version>String</version>
		</list-item>
		<list-item>
			<url>http://www.altova.com/</url>
			<type>String</type>
			<note>String</note>
			<version>String</version>
		</list-item>
	</download>
	<documentation>
		<list-item>
			<url>http://www.altova.com/</url>
			<type>
				<list-item>String</list-item>
				<list-item>String</list-item>
			</type>
			<note>String</note>
		</list-item>
		<list-item>
			<url>http://www.altova.com/</url>
			<type>
				<list-item>String</list-item>
				<list-item>String</list-item>
			</type>
			<note>String</note>
		</list-item>
	</documentation>
	<relation>
		<list-item>
			<biotoolsID>String</biotoolsID>
			<type>String</type>
		</list-item>
		<list-item>
			<biotoolsID>String</biotoolsID>
			<type>String</type>
		</list-item>
	</relation>
	<publication>
		<list-item>
			<doi>String</doi>
			<pmid>String</pmid>
			<pmcid>String</pmcid>
			<type>
				<list-item>String</list-item>
				<list-item>String</list-item>
			</type>
			<version>String</version>
			<note>String</note>
		</list-item>
		<list-item>
			<doi>String</doi>
			<pmid>String</pmid>
			<pmcid>String</pmcid>
			<type>
				<list-item>String</list-item>
				<list-item>String</list-item>
			</type>
			<version>String</version>
			<note>String</note>
		</list-item>
	</publication>
	<credit>
		<list-item>
			<name>String</name>
			<email>String</email>
			<url>http://www.altova.com/</url>
			<orcidid>String</orcidid>
			<gridid>String</gridid>
			<rorid>String</rorid>
			<fundrefid>String</fundrefid>
			<typeEntity>String</typeEntity>
			<typeRole>
				<list-item>String</list-item>
				<list-item>String</list-item>
			</typeRole>
			<note>String</note>
		</list-item>
		<list-item>
			<name>String</name>
			<email>String</email>
			<url>http://www.altova.com/</url>
			<orcidid>String</orcidid>
			<gridid>String</gridid>
			<rorid>String</rorid>
			<fundrefid>String</fundrefid>
			<typeEntity>String</typeEntity>
			<typeRole>
				<list-item>String</list-item>
				<list-item>String</list-item>
			</typeRole>
			<note>String</note>
		</list-item>
	</credit>
</root>
