=== bio-tools/biotoolsShim/xml2genericxml/biotools-2.0.0_framework.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="tools">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="root" maxOccurs="unbounded">
					<xs:complexType>
						<xs:sequence>
							<xs:element name="name" type="xs:string"/>
							<xs:element name="id" type="xs:string"/>
							<xs:element name="version" type="xs:string"/>
							<xs:element name="versionID" type="xs:string"/>
							<xs:element name="doi" type="xs:string"/>
							<xs:element name="shortDescription" type="xs:string"/>
							<xs:element name="description" type="xs:string"/>
							<xs:element name="homepage" type="xs:anyURI"/>
							<xs:element name="function">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="list-item" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="operation">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="list-item" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="uri" type="xs:anyURI"/>
																			<xs:element name="term" type="xs:string"/>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="input">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="list-item" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="data">
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element name="uri" type="xs:anyURI"/>
																						<xs:element name="term" type="xs:string"/>
																					</xs:sequence>
																				</xs:complexType>
																			</xs:element>
																			<xs:element name="format">
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element name="list-item" maxOccurs="unbounded">
																							<xs:complexType>
																								<xs:sequence>
																									<xs:element name="uri" type="xs:anyURI"/>
																									<xs:element name="term" type="xs:string"/>
																								</xs:sequence>
																							</xs:complexType>
																						</xs:element>
																					</xs:sequence>
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="output">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="list-item" maxOccurs="unbounded">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="data">
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element name="uri" type="xs:anyURI"/>
																						<xs:element name="term" type="xs:string"/>
																					</xs:sequence>
																				</xs:complexType>
																			</xs:element>
																			<xs:element name="format">
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element name="list-item" maxOccurs="unbounded">
																							<xs:complexType>
																								<xs:sequence>
																									<xs:element name="uri" type="xs:anyURI"/>
																									<xs:element name="term" type="xs:string"/>
																								</xs:sequence>
																							</xs:complexType>
																						</xs:element>
																					</xs:sequence>
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="comment" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="toolType">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="list-item" type="xs:string" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="topic">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="list-item" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="uri" type="xs:anyURI"/>
													<xs:element name="term" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="goTermID">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="list-item" type="xs:string" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="soTermID">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="list-item" type="xs:string" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="taxID">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="list-item" type="xs:short" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="operatingSystem">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="list-item" type="xs:string" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="language">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="list-item" type="xs:string" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="license" type="xs:string"/>
							<xs:element name="collectionID">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="list-item" type="xs:string" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="maturity" type="xs:string"/>
							<xs:element name="cost" type="xs:string"/>
							<xs:element name="accessibility">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="list-item" type="xs:string" maxOccurs="unbounded"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="relation">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="list-item" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="biotoolsId" type="xs:anyURI"/>
													<xs:element name="type" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="apiSpec">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="baseURL" type="xs:anyURI"/>
										<xs:element name="endpoint">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="list-item" maxOccurs="unbounded">
														<xs:complexType>
															<xs:sequence>
																<xs:element name="httpMethod" type="xs:string"/>
																<xs:element name="urlTemplate" type="xs:string"/>
																<xs:element name="output">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="list-item">
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element name="data">
																							<xs:complexType>
																								<xs:sequence>
																									<xs:element name="uri" type="xs:anyURI"/>
																									<xs:element name="term" type="xs:string"/>
																								</xs:sequence>
																							</xs:complexType>
																						</xs:element>
																						<xs:element name="format">
																							<xs:complexType>
																								<xs:sequence>
																									<xs:element name="list-item" maxOccurs="unbounded">
																										<xs:complexType>
																											<xs:sequence>
																												<xs:element name="uri" type="xs:anyURI"/>
																												<xs:element name="term" type="xs:string"/>
																											</xs:sequence>
																										</xs:complexType>
																									</xs:element>
																								</xs:sequence>
																							</xs:complexType>
																						</xs:element>
																					</xs:sequence>
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
																<xs:element name="summary" type="xs:string"/>
																<xs:element name="parameter">
																	<xs:complexType>
																		<xs:sequence>
																			<xs:element name="list-item" maxOccurs="unbounded">
																				<xs:complexType>
																					<xs:sequence>
																						<xs:element name="urlTemplateFragment" type="xs:string"/>
																						<xs:element name="data">
																							<xs:complexType>
																								<xs:sequence>
																									<xs:element name="uri" type="xs:anyURI"/>
																									<xs:element name="term" type="xs:string"/>
																								</xs:sequence>
																							</xs:complexType>
																						</xs:element>
																						<xs:element name="comment" type="xs:string"/>
																					</xs:sequence>
																				</xs:complexType>
																			</xs:element>
																		</xs:sequence>
																	</xs:complexType>
																</xs:element>
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="link">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="list-item" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="url" type="xs:anyURI"/>
													<xs:element name="type" type="xs:string"/>
													<xs:element name="comment" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="download">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="list-item" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="url" type="xs:anyURI"/>
													<xs:element name="type" type="xs:string"/>
													<xs:element name="comment" type="xs:string"/>
													<xs:element name="diskFormat" type="xs:string"/>
													<xs:element name="containerFormat" type="xs:string"/>
													<xs:element name="cmd" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="documentation">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="list-item" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="url" type="xs:anyURI"/>
													<xs:element name="type" type="xs:string"/>
													<xs:element name="comment" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="publication">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="list-item" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="doi" type="xs:string"/>
													<xs:element name="pmid" type="xs:string"/>
													<xs:element name="pmcid" type="xs:string"/>
													<xs:element name="type" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="contact">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="list-item" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="email" type="xs:string"/>
													<xs:element name="url" type="xs:anyURI"/>
													<xs:element name="name" type="xs:string"/>
													<xs:element name="tel" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="credit">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="list-item" maxOccurs="unbounded">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="name" type="xs:string"/>
													<xs:element name="email" type="xs:string"/>
													<xs:element name="url" type="xs:anyURI"/>
													<xs:element name="orcidId" type="xs:anyURI"/>
													<xs:element name="typeEntity" type="xs:string"/>
													<xs:element name="typeRole" type="xs:string"/>
													<xs:element name="comment" type="xs:string"/>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="elixirInfo">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="lastReviewExternalSab" type="xs:date"/>
										<xs:element name="lastReviewElixirSab" type="xs:date"/>
										<xs:element name="inSDP" type="xs:boolean"/>
										<xs:element name="isCoreDataResource" type="xs:boolean"/>
										<xs:element name="platform" type="xs:string"/>
										<xs:element name="node" type="xs:string"/>
										<xs:element name="comment" type="xs:string"/>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== bio-tools/biotoolsShim/utilities/removeEmptyElements/input.xml
<?xml version="1.0" encoding="UTF-8"?>
<tools xsi:noNamespaceSchemaLocation="D:/repos/GitHub/biotoolsShim/xml2genericxml/biotools-2.0.0_framework.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<root>
		<name>toolName</name>
		<id>toolName</id>
		<version>versionNumber</version>
		<versionID>1_0_0</versionID>
		<doi>doi:10.1093/nar/gkv1116</doi>
		<shortDescription>Short software description : a single declarative sentence in the present tense stating the tool function. Do not include tool name.</shortDescription>
		<description>Software description, e.g. a few sentences adapted from the software publication abstract or homepage.</description>
		<homepage>http://someURL.org</homepage>
		<function>
			<list-item>
				<operation>
					<list-item>
						<uri>http://edamontology.org/operation_0492</uri>
						<term>Multiple sequence alignment</term>
					</list-item>
					<list-item>
						<uri>http://edamontology.org/operation_0492</uri>
						<term>Multiple sequence alignment</term>
					</list-item>
				</operation>
				<input>
					<list-item>
						<data>
							<uri>http://edamontology.org/data_2976</uri>
							<term>Protein sequences</term>
						</data>
						<format>
							<list-item>
								<uri>http://edamontology.org/format_1929</uri>
								<term>FASTA</term>
							</list-item>
							<list-item>
								<uri>http://edamontology.org/format_1929</uri>
								<term>FASTA</term>
							</list-item>
						</format>
					</list-item>
					<list-item>
						<data>
							<uri>http://edamontology.org/data_2976</uri>
							<term>Protein sequences</term>
						</data>
						<format>
							<list-item>
								<uri>http://edamontology.org/format_1929</uri>
								<term>FASTA</term>
							</list-item>
							<list-item>
								<uri>http://edamontology.org/format_1929</uri>
								<term>FASTA</term>
							</list-item>
						</format>
					</list-item>
				</input>
				<output>
					<list-item>
						<data>
							<uri>http://edamontology.org/data_2976</uri>
							<term>Protein sequences</term>
						</data>
						<format>
							<list-item>
								<uri>http://edamontology.org/format_1929</uri>
								<term>FASTA</term>
							</list-item>
							<list-item>
								<uri>http://edamontology.org/format_1929</uri>
								<term>FASTA</term>
							</list-item>
						</format>
					</list-item>
					<list-item>
						<data>
							<uri>http://edamontology.org/data_2976</uri>
							<term>Protein sequences</term>
						</data>
						<format>
							<list-item>
								<uri>http://edamontology.org/format_1929</uri>
								<term>FASTA</term>
							</list-item>
							<list-item>
								<uri>http://edamontology.org/format_1929</uri>
								<term>FASTA</term>
							</list-item>
						</format>
					</list-item>
				</output>
				<comment>Concise comment about this function, if not apparent from the software description and EDAM annotations.</comment>
			</list-item>
			<list-item>
				<operation>
					<list-item>
						<uri>http://edamontology.org/operation_0492</uri>
						<term>Multiple sequence alignment</term>
					</list-item>
					<list-item>
						<uri>http://edamontology.org/operation_0492</uri>
						<term>Multiple sequence alignment</term>
					</list-item>
				</operation>
				<input>
					<list-item>
						<data>
							<uri>http://edamontology.org/data_2976</uri>
							<term>Protein sequences</term>
						</data>
						<format>
							<list-item>
								<uri>http://edamontology.org/format_1929</uri>
								<term>FASTA</term>
							</list-item>
							<list-item>
								<uri>http://edamontology.org/format_1929</uri>
								<term>FASTA</term>
							</list-item>
						</format>
					</list-item>
					<list-item>
						<data>
							<uri>http://edamontology.org/data_2976</uri>
							<term>Protein sequences</term>
						</data>
						<format>
							<list-item>
								<uri>http://edamontology.org/format_1929</uri>
								<term>FASTA</term>
							</list-item>
							<list-item>
								<uri>http://edamontology.org/format_1929</uri>
								<term>FASTA</term>
							</list-item>
						</format>
					</list-item>
				</input>
				<output>
					<list-item>
						<data>
							<uri>http://edamontology.org/data_2976</uri>
							<term>Protein sequences</term>
						</data>
						<format>
							<list-item>
								<uri>http://edamontology.org/format_1929</uri>
								<term>FASTA</term>
							</list-item>
							<list-item>
								<uri>http://edamontology.org/format_1929</uri>
								<term>FASTA</term>
							</list-item>
						</format>
					</list-item>
					<list-item>
						<data>
							<uri>http://edamontology.org/data_2976</uri>
							<term>Protein sequences</term>
						</data>
						<format>
							<list-item>
								<uri>http://edamontology.org/format_1929</uri>
								<term>FASTA</term>
							</list-item>
							<list-item>
								<uri>http://edamontology.org/format_1929</uri>
								<term>FASTA</term>
							</list-item>
						</format>
					</list-item>
				</output>
				<comment>Concise comment about this function, if not apparent from the software description and EDAM annotations.</comment>
			</list-item>
		</function>
		<toolType>
			<list-item>Plug-in</list-item>
			<list-item>Web application</list-item>
		</toolType>
		<topic>
			<list-item>
				<uri>http://edamontology.org/topic_0121</uri>
				<term>Proteomics</term>
			</list-item>
			<list-item>
				<uri>http://edamontology.org/topic_0121</uri>
				<term>Proteomics</term>
			</list-item>
		</topic>
		<goTermID>
			<list-item>GO:0005125</list-item>
			<list-item>0005125</list-item>
		</goTermID>
		<soTermID>
			<list-item>0000307</list-item>
			<list-item>0000307</list-item>
		</soTermID>
		<taxID>
			<list-item>9606</list-item>
			<list-item>9606</list-item>
		</taxID>
		<operatingSystem>
			<list-item>Windows</list-item>
			<list-item>Linux</list-item>
		</operatingSystem>
		<language>
			<list-item>Javascript</list-item>
			<list-item>Other</list-item>
		</language>
		<license>CC-BY-1.0</license>
		<collectionID>
			<list-item>collectionName</list-item>
			<list-item>collectionName</list-item>
		</collectionID>
		<maturity>Mature</maturity>
		<cost>Free of charge</cost>
		<accessibility/>
		<relation>
			<list-item>
				<biotoolsId>https://bio.tools/tool/toolName/version/versionNumber</biotoolsId>
				<type>includedIn</type>
			</list-item>
			<list-item>
				<biotoolsId>https://bio.tools/tool/toolName/version/versionNumber</biotoolsId>
				<type>isPluginFor</type>
			</list-item>
		</relation>
		<apiSpec>
			<baseURL>https://bio.tools</baseURL>
			<endpoint>
				<list-item>
					<httpMethod>GET</httpMethod>
					<urlTemplate>/tool/{toolID}</urlTemplate>
					<output>
						<list-item>
							<data>
								<uri>http://edamontology.org/data_2976</uri>
								<term>Protein sequences</term>
							</data>
							<format>
								<list-item>
									<uri>http://edamontology.org/format_1929</uri>
									<term>FASTA</term>
								</list-item>
								<list-item>
									<uri>http://edamontology.org/format_1929</uri>
									<term>FASTA</term>
								</list-item>
							</format>
						</list-item>
					</output>
					<summary>a</summary>
					<parameter>
						<list-item>
							<urlTemplateFragment>{toolID}</urlTemplateFragment>
							<data>
								<uri>http://edamontology.org/data_2976</uri>
								<term>Protein sequences</term>
							</data>
							<comment>a</comment>
						</list-item>
						<list-item>
							<urlTemplateFragment>{toolID}</urlTemplateFragment>
							<data>
								<uri>http://edamontology.org/data_2976</uri>
								<term>Protein sequences</term>
							</data>
							<comment>a</comment>
						</list-item>
					</parameter>
				</list-item>
				<list-item>
					<httpMethod>GET</httpMethod>
					<urlTemplate>/tool/{toolID}</urlTemplate>
					<output>
						<list-item>
							<data>
								<uri>http://edamontology.org/data_2976</uri>
								<term>Protein sequences</term>
							</data>
							<format>
								<list-item>
									<uri>http://edamontology.org/format_1929</uri>
									<term>FASTA</term>
								</list-item>
								<list-item>
									<uri>http://edamontology.org/format_1929</uri>
									<term>FASTA</term>
								</list-item>
							</format>
						</list-item>
					</output>
					<summary>a</summary>
					<parameter>
						<list-item>
							<urlTemplateFragment>{toolID}</urlTemplateFragment>
							<data>
								<uri>http://edamontology.org/data_2976</uri>
								<term>Protein sequences</term>
							</data>
							<comment>a</comment>
						</list-item>
						<list-item>
							<urlTemplateFragment>{toolID}</urlTemplateFragment>
							<data>
								<uri>http://edamontology.org/data_2976</uri>
								<term>Protein sequences</term>
							</data>
							<comment>a</comment>
						</list-item>
					</parameter>
				</list-item>
			</endpoint>
		</apiSpec>
		<link>
			<list-item>
				<url>http://someURL.org</url>
				<type>Mailing list</type>
				<comment>text</comment>
			</list-item>
			<list-item>
				<url>http://someURL.org</url>
				<type>Social media</type>
				<comment>text</comment>
			</list-item>
		</link>
		<download>
			<list-item>
				<url>http://someURL.org</url>
				<type>Tool wrapper (galaxy)</type>
				<comment>a</comment>
				<diskFormat>vhd</diskFormat>
				<containerFormat>singularity</containerFormat>
				<cmd>a</cmd>
			</list-item>
			<list-item>
				<url>http://someURL.org</url>
				<type>Command-line specification</type>
				<comment>a</comment>
				<diskFormat>vmdk</diskFormat>
				<containerFormat>bare</containerFormat>
				<cmd>a</cmd>
			</list-item>
		</download>
		<documentation>
			<list-item>
				<url>http://someURL.org</url>
				<type>Citation instructions</type>
				<comment>a</comment>
			</list-item>
			<list-item>
				<url>http://someURL.org</url>
				<type>General</type>
				<comment>a</comment>
			</list-item>
		</documentation>
		<publication>
			<list-item>
				<doi>doi:10.1093/nar/gkv1116</doi>
